import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/components/organism/header";
import Footer from "@/components/organism/footer";

const raleway = Raleway({
    subsets: ["latin"],
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body className={raleway.className}>
                <Header />
                <main className="container">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
